[features]
seeds = false
skip-lint = false
[programs.localnet]
rocket = "3PhaPMTdNzWpgyRDqsizW2teansweaYWBQ3somsUP13z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
