export { newGame } from "./newGame"
export type { NewGameAccounts } from "./newGame"
export { newPlayer } from "./newPlayer"
export type { NewPlayerArgs, NewPlayerAccounts } from "./newPlayer"
export { newPiece } from "./newPiece"
export type { NewPieceArgs, NewPieceAccounts } from "./newPiece"
export { movePiece } from "./movePiece"
export type { MovePieceAccounts } from "./movePiece"
